#!/usr/bin/env python3
"""
build_font.py — compile a real Phonoglyph .ttf from a base font + respellings.json.

Pipeline:
  1. load a base font (default: DejaVuSans.ttf)
  2. add one empty control glyph  w_<word>  per dictionary word
  3. emit BOUNDARY-GUARDED GSUB rules into Phonoglyph.fea:
       collapse (contextual ligature, guarded so it only fires on whole words)
       expand   (multiple substitution -> the respelling glyphs)
  4. merge features, rename to Phonoglyph, save Phonoglyph.ttf
  5. reload and report GSUB stats

Boundary guard: `ignore sub @letter <word>;` / `ignore sub <word> @letter;` means
the collapse only fires when the letters are NOT adjacent to another letter — i.e.
a whole word. So "the" does NOT fire inside "there".

Usage:
    python3 build_font.py [base.ttf] [respellings.json]
"""
import json
import os
import sys
from fontTools.ttLib import TTFont
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.feaLib.builder import addOpenTypeFeatures

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
DICT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, "respellings.json")
OUT_TTF = os.path.join(HERE, "Phonoglyph.ttf")
OUT_FEA = os.path.join(HERE, "Phonoglyph.fea")


def main():
    font = TTFont(BASE)
    cmap = font.getBestCmap()

    def gname(ch):
        return cmap.get(ord(ch))

    letters = [gname(c) for c in "abcdefghijklmnopqrstuvwxyz"]
    if any(g is None for g in letters):
        print("base font is missing a-z glyphs; pick another base", file=sys.stderr)
        return 1
    hyphen = gname("-")

    with open(DICT, encoding="utf-8") as fh:
        data = json.load(fh)

    pairs = []
    for word, respell in data.items():
        if word.startswith("_"):
            continue
        word = word.lower()
        if not word.isalpha() or not all("a" <= c <= "z" for c in word):
            continue
        # resolve glyph names for the respelling (letters + hyphen)
        rg = []
        ok = True
        for c in respell:
            g = hyphen if c == "-" else gname(c)
            if g is None:
                ok = False
                break
            rg.append(g)
        if not ok:
            continue
        wg = [gname(c) for c in word]
        if any(g is None for g in wg):
            continue
        pairs.append((word, wg, rg))

    # longest words first so the greedy shaper prefers the longest whole-word match
    pairs.sort(key=lambda p: len(p[0]), reverse=True)

    # 2. add empty control glyphs
    glyf = font["glyf"]
    hmtx = font["hmtx"]
    order = font.getGlyphOrder()
    controls = [f"w_{w}" for w, _, _ in pairs]
    new = [c for c in controls if c not in glyf]
    font.setGlyphOrder(order + new)
    empty = TTGlyphPen(None).glyph()
    for name in new:
        glyf[name] = empty
        hmtx[name] = (0, 0)

    # 3. emit the guarded feature file
    letter_class = "@letter = [" + " ".join(letters) + "];"
    collapse = ["lookup phonoglyph_collapse {"]
    for (word, wg, _), ctrl in zip(pairs, controls):
        marked = " ".join(g + "'" for g in wg)
        collapse.append(f"    ignore sub @letter {marked};")
        collapse.append(f"    ignore sub {marked} @letter;")
        collapse.append(f"    sub {marked} by {ctrl};")
    collapse.append("} phonoglyph_collapse;")

    expand = ["lookup phonoglyph_expand {"]
    for (_, _, rg), ctrl in zip(pairs, controls):
        expand.append(f"    sub {ctrl} by {' '.join(rg)};")
    expand.append("} phonoglyph_expand;")

    fea = "\n".join([
        "# Phonoglyph — generated by build_font.py (boundary-guarded G2P in GSUB)",
        letter_class, "",
        "\n".join(collapse), "",
        "\n".join(expand), "",
        "feature calt {",
        "    lookup phonoglyph_collapse;",
        "    lookup phonoglyph_expand;",
        "} calt;",
        "",
    ])
    with open(OUT_FEA, "w", encoding="utf-8") as fh:
        fh.write(fea)

    # 4. merge + rename + save
    addOpenTypeFeatures(font, OUT_FEA)
    name = font["name"]
    for nid, val in [(1, "Phonoglyph"), (4, "Phonoglyph Regular"),
                     (6, "Phonoglyph-Regular"), (16, "Phonoglyph")]:
        name.setName(val, nid, 3, 1, 0x409)
        name.setName(val, nid, 1, 0, 0)
    font.save(OUT_TTF)

    # 5. verify
    check = TTFont(OUT_TTF)
    gsub = check["GSUB"].table
    n_lookups = len(gsub.LookupList.Lookup)
    n_feats = len(gsub.FeatureList.FeatureRecord)
    print(f"OK: wrote {os.path.basename(OUT_TTF)}")
    print(f"    words baked : {len(pairs)}")
    print(f"    control glyphs added : {len(new)}")
    print(f"    GSUB features : {n_feats}, lookups : {n_lookups}")
    print(f"    feature file  : {os.path.basename(OUT_FEA)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
