#!/usr/bin/env python3
"""
generate_fea.py — turn respellings.json into an OpenType feature file (GSUB).

Strategy (two-stage, so copy-paste stays lossless — GSUB only swaps *glyphs*,
the backing Unicode text is untouched):

  stage 1  (ligature / GSUB4):  collapse a word's letters into one control glyph
              sub t h r o u g h by w_through ;
  stage 2  (multiple  / GSUB2): expand the control glyph into respelling glyphs
              sub w_through by t h r o o ;

The build step (fontTools/feaLib) must add the intermediate control glyphs
(w_<word>) to the font — this script prints the list it needs at the top.

⚠️ KNOWN GAP (the real weekend work): these rules fire on substrings too
("through" inside "throughput"). Production needs contextual guards that require
a word boundary on both sides. That is the genuine "font hell" — see README.

Usage:
    python3 generate_fea.py respellings.json > respell.fea
"""
import json
import re
import sys

WORD_RE = re.compile(r"^[a-z]+$")
RESPELL_RE = re.compile(r"^[a-z-]+$")

GLYPH = {"-": "hyphen"}  # respelling letters map to their own glyph; hyphen is named


def glyphs_for(text):
    """Space-separated glyph names for a run of respelling/word characters."""
    return " ".join(GLYPH.get(c, c) for c in text)


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 1
    with open(argv[1], encoding="utf-8") as fh:
        data = json.load(fh)

    pairs = []
    for word, respell in data.items():
        if word.startswith("_"):
            continue
        word = word.lower()
        if not WORD_RE.match(word) or not RESPELL_RE.match(respell):
            continue
        pairs.append((word, respell))
    # longest words first so ligatures prefer the longest match
    pairs.sort(key=lambda p: len(p[0]), reverse=True)

    controls = [f"w_{w}" for w, _ in pairs]
    out = []
    out.append("# Phonoglyph GSUB feature file — generated by generate_fea.py")
    out.append("# Add these intermediate control glyphs to the font before compiling:")
    out.append("#   " + " ".join(controls))
    out.append("# See README 'Honest limits' — word-boundary guards are still TODO.")
    out.append("")
    out.append("feature calt {")
    out.append("    # --- stage 1: collapse whole words into a control glyph ---")
    for word, _ in pairs:
        out.append(f"    sub {glyphs_for(word)} by w_{word};")
    out.append("")
    out.append("    # --- stage 2: expand control glyphs into the respelling ---")
    for word, respell in pairs:
        out.append(f"    sub w_{word} by {glyphs_for(respell)};")
    out.append("} calt;")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
