/**
 * Emits the on-device SQLite seed: the schema plus the immutable infrastructure
 * data the Expo client ships with.
 *
 *   npm run build:sqlite --workspace=@streetlevel/data
 *
 * This is the "Immutable Static Infrastructure Data" half of the storage design
 * — station complexes, entrances, passageways and exit alignments. It changes
 * with an app release, not with a sync, which is why it is generated as a flat
 * SQL file the client executes once on first launch.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { ON_DEVICE_SCHEMA_SQL } from '@streetlevel/shared';

import { buildNetwork } from '../build-network.js';
import { MICRO_NAV } from '../micronav.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const GTFS_DIR = path.resolve(here, '../../vendor/gtfs');
const OUT_DIR = path.resolve(here, '../../generated');

/** SQLite string literal quoting. */
function q(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'NULL';
  return `'${value.replace(/'/g, "''")}'`;
}

async function main(): Promise<void> {
  const network = await buildNetwork({ gtfsDir: GTFS_DIR });
  const lines: string[] = [
    '-- Generated by @streetlevel/data. Do not edit by hand.',
    '-- Schema comes from @streetlevel/shared so the generator and the client',
    '-- cannot drift apart. Regenerate with: npm run build:sqlite',
    ON_DEVICE_SCHEMA_SQL,
    'BEGIN TRANSACTION;',
  ];

  for (const station of Object.values(network.stations)) {
    lines.push(
      `INSERT OR REPLACE INTO mta_stations VALUES (${q(station.id)}, ${q(station.complexId)}, ` +
        `${q(station.name)}, ${q(station.borough)}, ${q(station.lines.join(','))}, ` +
        `${station.latitude}, ${station.longitude});`,
    );
  }

  // Only entrances whose station survived the graph build can be inserted; the
  // foreign key would reject the rest, and a dangling entrance is a bug anyway.
  const known = new Set(Object.keys(network.stations));
  let skipped = 0;

  for (const e of MICRO_NAV.entrances) {
    if (!known.has(e.stationId)) {
      skipped += 1;
      continue;
    }
    lines.push(
      `INSERT OR REPLACE INTO station_entrances VALUES (${q(e.entranceId)}, ${q(e.stationId)}, ` +
        `${q(e.streetName)}, ${q(e.crossStreet)}, ${q(e.cornerCode)}, ${q(e.entranceType)}, ` +
        `${e.hasOmnyTurnstile ? 1 : 0}, ${q(e.landmarkDescription)}, ${q(e.avoidanceNotes)}, ` +
        `${e.latitude}, ${e.longitude}, ${q(e.provenance)}, ${q(e.surveyedOn)});`,
    );
  }

  for (const c of MICRO_NAV.platformConnections) {
    if (!known.has(c.originStationId)) {
      skipped += 1;
      continue;
    }
    lines.push(
      `INSERT OR REPLACE INTO platform_connections VALUES (${q(c.connectionId)}, ${q(c.originStationId)}, ` +
        `${q(c.targetLineId)}, ${q(c.directionBound)}, ${q(c.walkingPathInstructions)}, ` +
        `${q(JSON.stringify(c.ceilingSignMarkers))}, ${q(c.avoidanceTrackNoise)}, ` +
        `${q(c.provenance)}, ${q(c.surveyedOn)});`,
    );
  }

  for (const a of MICRO_NAV.exitCarAlignments) {
    if (!known.has(a.originStationId) || !known.has(a.destinationStationId)) {
      skipped += 1;
      continue;
    }
    lines.push(
      `INSERT OR REPLACE INTO exit_car_alignments VALUES (${q(a.alignmentId)}, ${q(a.originStationId)}, ` +
        `${q(a.destinationStationId)}, ${q(a.transitLineId)}, ${a.optimalCarIndex}, ` +
        `${q(a.platformLandmarkMarker)}, ${q(a.exitStairwellIdentifier)}, ` +
        `${q(a.surfacingStreetCorner)}, ${q(a.provenance)}, ${q(a.surveyedOn)});`,
    );
  }

  lines.push('COMMIT;', '');

  await mkdir(OUT_DIR, { recursive: true });
  const outPath = path.join(OUT_DIR, 'seed.sql');
  await writeFile(outPath, lines.join('\n'), 'utf8');

  const surveyed = MICRO_NAV.entrances.filter((e) => e.provenance === 'FIELD_SURVEYED').length;
  process.stdout.write(
    [
      '',
      `  stations            ${Object.keys(network.stations).length}`,
      `  entrances           ${MICRO_NAV.entrances.length} (${surveyed} field-surveyed)`,
      `  platform passages   ${MICRO_NAV.platformConnections.length}`,
      `  exit alignments     ${MICRO_NAV.exitCarAlignments.length}`,
      skipped > 0 ? `  skipped (no station)${String(skipped).padStart(4)}` : '',
      `  written to          ${outPath}`,
      '',
    ]
      .filter(Boolean)
      .join('\n'),
  );
}

main().catch((err) => {
  process.stderr.write(`${err instanceof Error ? err.stack : String(err)}\n`);
  process.exit(1);
});
